// Command warp-reg is the entrypoint for the warp-wireproxy container.
//
// It registers an anonymous Cloudflare WARP device, renders a wireproxy
// configuration file from the environment, and then hands off to wireproxy.
// It also serves as the container HEALTHCHECK and, optionally, as a Prometheus
// exporter for wireproxy's own health endpoint.
//
// It deliberately depends on nothing outside the standard library, so the
// runtime image needs no shell, curl, jq or openssl.
package main

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"os/signal"
	"syscall"
	"time"
)

// version is stamped at build time with -ldflags "-X main.version=...".
var version = "dev"

// defaultWireproxyBin is where the image puts wireproxy. WIREPROXY_BIN
// overrides it, which is what the test suite uses to run against a locally
// built binary.
const defaultWireproxyBin = "/usr/bin/wireproxy"

func wireproxyBinary() string { return env("WIREPROXY_BIN", defaultWireproxyBin) }

func main() {
	cmd := "run"
	if len(os.Args) > 1 {
		cmd = os.Args[1]
	}

	var err error
	switch cmd {
	case "run":
		err = cmdRun()
	case "health":
		err = cmdHealth()
	case "config":
		err = cmdConfig()
	case "metrics":
		err = cmdMetrics()
	case "version", "-v", "--version":
		fmt.Printf("warp-reg %s\n", version)
		return
	case "help", "-h", "--help":
		usage()
		return
	default:
		fmt.Fprintf(os.Stderr, "warp-reg: unknown command %q\n\n", cmd)
		usage()
		os.Exit(2)
	}

	if err != nil {
		fmt.Fprintf(os.Stderr, "warp-reg: %v\n", err)
		os.Exit(1)
	}
}

func usage() {
	fmt.Print(`warp-reg -- entrypoint and health tooling for warp-wireproxy

Usage:
  warp-reg [run]     register with WARP, write the config, exec wireproxy
  warp-reg health    probe wireproxy's /readyz endpoint (container HEALTHCHECK)
  warp-reg config    print the config that would be generated, then exit
  warp-reg metrics   print Prometheus metrics once, then exit
  warp-reg version   print the version

Configuration is entirely via environment variables; see the README.
`)
}

// cmdRun is the container entrypoint.
func cmdRun() error {
	s, err := LoadSettings()
	if err != nil {
		return err
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// Check the ports before registering: a clash is a configuration mistake,
	// and there is no reason to enrol a device with Cloudflare that we are
	// about to abandon when wireproxy fails to bind.
	if err := PreflightPorts(s); err != nil {
		return err
	}

	// A config present at the target path is bring-your-own and is never
	// overwritten -- unless we wrote it ourselves on an earlier boot, in which
	// case it is regenerated so that environment changes actually take effect.
	_, statErr := os.Stat(s.ConfPath)
	if statErr == nil && !IsGeneratedConfig(s.ConfPath) {
		logf("using operator-supplied config at %s (skipping WARP registration)", s.ConfPath)
	} else {
		if statErr == nil {
			logf("regenerating %s (previously generated by warp-reg)", s.ConfPath)
		}
		reg := &Registration{}
		if s.WGConfig == "" {
			if reg, err = EnsureRegistration(ctx, s); err != nil {
				return err
			}
		} else {
			logf("using WireGuard config at %s (skipping WARP registration)", s.WGConfig)
		}

		if err := WriteConfig(s.ConfPath, RenderConfig(s, reg)); err != nil {
			return err
		}
		logf("wrote %s", s.ConfPath)
	}

	bin := wireproxyBinary()
	args := []string{bin, "-c", s.ConfPath}
	if s.InfoBind != "" {
		args = append(args, "-i", s.InfoBind)
	}
	if s.Silent {
		args = append(args, "-s")
	}

	// Without the exporter there is nothing for this process to do once
	// wireproxy is up, so hand over the PID entirely: wireproxy becomes PID 1
	// and receives signals directly, with no supervisor in the way.
	if s.MetricsBind == "" {
		logf("exec %v", args)
		return syscall.Exec(bin, args, os.Environ())
	}

	return supervise(ctx, s, args)
}

// supervise runs wireproxy as a child while this process serves the Prometheus
// exporter, forwarding termination signals and exiting with the child's status.
func supervise(ctx context.Context, s *Settings, args []string) error {
	logf("starting %v", args)

	child := exec.Command(args[0], args[1:]...)
	child.Stdout = os.Stdout
	child.Stderr = os.Stderr
	child.Env = os.Environ()
	if err := child.Start(); err != nil {
		return fmt.Errorf("starting wireproxy: %w", err)
	}

	exporterCtx, stopExporter := context.WithCancel(ctx)
	defer stopExporter()
	go func() {
		if err := ServeMetrics(exporterCtx, s.MetricsBind, NewExporter(s.InfoBind, version)); err != nil {
			logf("prometheus exporter stopped: %v", err)
		}
	}()

	done := make(chan error, 1)
	go func() { done <- child.Wait() }()

	select {
	case err := <-done:
		stopExporter()
		return exitLike(err)

	case <-ctx.Done():
		logf("received shutdown signal, stopping wireproxy")
		_ = child.Process.Signal(syscall.SIGTERM)
		stopExporter()

		select {
		case err := <-done:
			return exitLike(err)
		case <-time.After(10 * time.Second):
			logf("wireproxy did not exit within 10s, killing")
			_ = child.Process.Kill()
			<-done
			return nil
		}
	}
}

// exitLike mirrors the child's exit status into our own, so `docker inspect`
// reports what wireproxy actually did.
func exitLike(err error) error {
	if err == nil {
		return nil
	}
	var ee *exec.ExitError
	if errors.As(err, &ee) {
		os.Exit(ee.ExitCode())
	}
	return err
}

// cmdHealth is the container HEALTHCHECK. It asks wireproxy whether its
// CheckAlive targets are still answering through the tunnel, which is a real
// end-to-end signal: the ICMP echo traverses the WireGuard tunnel to
// Cloudflare and back.
func cmdHealth() error {
	s, err := LoadSettings()
	if err != nil {
		return err
	}
	if s.InfoBind == "" {
		return fmt.Errorf("INFO_BIND is empty, so there is no health endpoint to probe")
	}

	// The health endpoint binds to a specific address; probing 0.0.0.0 does
	// not work, so rewrite a wildcard bind to loopback.
	addr := loopbackize(s.InfoBind)

	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Get("http://" + addr + "/readyz")
	if err != nil {
		return fmt.Errorf("probing %s: %w", addr, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("wireproxy /readyz returned %s", resp.Status)
	}
	return nil
}

// cmdConfig renders the configuration without starting anything, for
// debugging what the environment actually produced.
func cmdConfig() error {
	s, err := LoadSettings()
	if err != nil {
		return err
	}
	reg := &Registration{
		PrivateKey: "<generated at runtime>",
		PeerKey:    "<from Cloudflare>",
		AddressV4:  "0.0.0.0",
		AddressV6:  "::",
	}
	if s.WGConfig == "" {
		ctx, cancel := context.WithTimeout(context.Background(), s.Timeout)
		defer cancel()
		if live, err := EnsureRegistration(ctx, s); err == nil {
			reg = live
		} else {
			logf("could not obtain a live registration (%v); showing placeholders", err)
		}
	}
	fmt.Print(RenderConfig(s, reg))
	return nil
}

// cmdMetrics prints one Prometheus scrape to stdout.
func cmdMetrics() error {
	s, err := LoadSettings()
	if err != nil {
		return err
	}
	if s.InfoBind == "" {
		return fmt.Errorf("INFO_BIND is empty, so there is nothing to scrape")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	fmt.Print(NewExporter(loopbackize(s.InfoBind), version).Gather(ctx))
	return nil
}

func logf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "[warp-reg] "+format+"\n", args...)
}
