package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// RenderConfig produces a wireproxy configuration file.
//
// Multi-valued keys (Address, AllowedIPs, DNS, CheckAlive) are emitted as a
// single comma-separated line, never as repeated keys. wireproxy loads its ini
// with AllowShadows, but every one of these parsers reads the key via
// key.String() -- which returns only the FIRST occurrence -- and then splits on
// commas itself. Writing them on separate lines silently discards everything
// after the first, which costs you the IPv6 address and the ::/0 route.
// GeneratedMarker is the first line of every config warp-reg writes. It is how
// a later start tells a file it generated itself (safe to overwrite, so that
// environment changes take effect) from one an operator supplied (must be left
// alone). Without it, the config we wrote on first boot would be mistaken for a
// user's on every subsequent boot, and no environment change would ever apply.
const GeneratedMarker = "# Generated by warp-reg"

func RenderConfig(s *Settings, reg *Registration) string {
	var b strings.Builder

	b.WriteString(GeneratedMarker + ". Changes are overwritten on restart.\n")
	b.WriteString("# Mount your own file at " + s.ConfPath + " to take over completely.\n\n")

	if s.WGConfig != "" {
		// Bring-your-own WireGuard peer: wireproxy reads [Interface]/[Peer]
		// from the referenced file and we contribute only the proxy sections.
		fmt.Fprintf(&b, "WGConfig = %s\n\n", s.WGConfig)
	} else {
		b.WriteString("[Interface]\n")
		fmt.Fprintf(&b, "PrivateKey = %s\n", reg.PrivateKey)
		fmt.Fprintf(&b, "Address = %s/32, %s/128\n", reg.AddressV4, reg.AddressV6)
		if len(s.DNS) > 0 {
			fmt.Fprintf(&b, "DNS = %s\n", strings.Join(s.DNS, ", "))
		}
		fmt.Fprintf(&b, "MTU = %d\n", s.MTU)
		if len(s.CheckAlive) > 0 {
			fmt.Fprintf(&b, "CheckAlive = %s\n", strings.Join(s.CheckAlive, ", "))
			fmt.Fprintf(&b, "CheckAliveInterval = %d\n", s.CheckAliveInterval)
		}
		b.WriteString("\n[Peer]\n")
		fmt.Fprintf(&b, "PublicKey = %s\n", reg.PeerKey)
		b.WriteString("AllowedIPs = 0.0.0.0/0, ::/0\n")
		fmt.Fprintf(&b, "Endpoint = %s\n", s.Endpoint)
		fmt.Fprintf(&b, "PersistentKeepalive = %d\n", s.Keepalive)
	}

	// Section name is [Socks5]; wireproxy loads the ini case-insensitively.
	if s.Socks5.Enabled() {
		b.WriteString("\n[Socks5]\n")
		fmt.Fprintf(&b, "BindAddress = %s\n", s.Socks5.Bind)
		writeCredentials(&b, s.Socks5)
	}

	if s.HTTP.Enabled() {
		b.WriteString("\n[http]\n")
		fmt.Fprintf(&b, "BindAddress = %s\n", s.HTTP.Bind)
		writeCredentials(&b, s.HTTP)
	}

	if s.ExtraConfig != "" {
		b.WriteString("\n# --- EXTRA_CONFIG ---\n")
		b.WriteString(strings.TrimRight(s.ExtraConfig, "\n"))
		b.WriteString("\n")
	}

	return b.String()
}

func writeCredentials(b *strings.Builder, l Listener) {
	if l.Username == "" {
		return
	}
	fmt.Fprintf(b, "Username = %s\n", l.Username)
	fmt.Fprintf(b, "Password = %s\n", l.Password)
}

// WriteConfig writes the rendered config with 0600 permissions, since it
// contains the tunnel private key and any proxy credentials.
func WriteConfig(path, contents string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("creating %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// IsGeneratedConfig reports whether the file at path was written by warp-reg,
// as opposed to being supplied by the operator. A file we cannot read is
// treated as not ours, so the failure mode is leaving it alone.
func IsGeneratedConfig(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()

	buf := make([]byte, len(GeneratedMarker))
	if _, err := io.ReadFull(f, buf); err != nil {
		return false
	}
	return string(buf) == GeneratedMarker
}
