# TorGuard WireGuard Config
[Interface]
PrivateKey = 
ListenPort = 53870
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.26.25/24

[Peer]
PublicKey = fVH86Icx7tUquYlhd8BZXQFwjkeax8MhJHAsk0ikqXA=
AllowedIPs = 0.0.0.0/0
Endpoint = 31.40.212.136:1443
PersistentKeepalive = 25
