# TorGuard WireGuard Config
[Interface]
PrivateKey = 
ListenPort = 60190
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.33.225/24

[Peer]
PublicKey = LrdrEaCYPC6k3gy97Gj97EL4w6KahQ+e1AZ6MazEt0Y=
AllowedIPs = 0.0.0.0/0
Endpoint = 31.40.212.88:1443
PersistentKeepalive = 25
