# TorGuard WireGuard Config
[Interface]
PrivateKey = 
ListenPort = 53497
MTU = 1390
DNS = 1.1.1.1
Address = 10.13.29.137/24

[Peer]
PublicKey = 4NDhSdbJzsXpifs8U10I5jTmUwEaU2Uj/8TEyyrp6H4=
AllowedIPs = 0.0.0.0/0
Endpoint = 31.40.212.42:1443
PersistentKeepalive = 25
